server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway?currentSchema=backend-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect